import type { ProviderPreset } from '@yys/shared';

export const providerPresets: ProviderPreset[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek 深度求索',
    kind: 'deepseek',
    defaultBaseURL: 'https://api.deepseek.com',
    requiresKey: true,
    keyUrl: 'https://platform.deepseek.com/api_keys',
    editableBaseURL: false,
    group: 'domestic',
  },
  {
    id: 'dashscope',
    name: '阿里云百炼（通义千问）',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    requiresKey: true,
    keyUrl: 'https://bailian.console.aliyun.com/',
    editableBaseURL: false,
    group: 'domestic',
  },
  {
    id: 'moonshot',
    name: '月之暗面 Kimi',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://api.moonshot.cn/v1',
    requiresKey: true,
    keyUrl: 'https://platform.moonshot.cn/console/api-keys',
    editableBaseURL: false,
    group: 'domestic',
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://open.bigmodel.cn/api/paas/v4',
    requiresKey: true,
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    editableBaseURL: false,
    group: 'domestic',
  },
  {
    id: 'volcengine',
    name: '火山方舟（豆包）',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://ark.cn-beijing.volces.com/api/v3',
    requiresKey: true,
    keyUrl: 'https://console.volcengine.com/ark',
    editableBaseURL: false,
    group: 'domestic',
  },
  {
    id: 'minimax',
    name: 'MiniMax 海螺',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://api.minimax.cn/v1',
    requiresKey: true,
    keyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    editableBaseURL: true,
    group: 'domestic',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    kind: 'openai',
    defaultBaseURL: 'https://api.openai.com/v1',
    requiresKey: true,
    keyUrl: 'https://platform.openai.com/api-keys',
    editableBaseURL: true,
    group: 'international',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    kind: 'anthropic',
    defaultBaseURL: 'https://api.anthropic.com/v1',
    requiresKey: true,
    keyUrl: 'https://console.anthropic.com/settings/keys',
    editableBaseURL: true,
    group: 'international',
  },
  {
    id: 'google',
    name: 'Google Gemini',
    kind: 'google',
    defaultBaseURL: 'https://generativelanguage.googleapis.com/v1beta',
    requiresKey: true,
    keyUrl: 'https://aistudio.google.com/apikey',
    editableBaseURL: true,
    group: 'international',
  },
  {
    id: 'siliconflow',
    name: '硅基流动 SiliconFlow',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://api.siliconflow.cn/v1',
    requiresKey: true,
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    editableBaseURL: false,
    group: 'aggregator',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    kind: 'openai-compatible',
    defaultBaseURL: 'https://openrouter.ai/api/v1',
    requiresKey: true,
    keyUrl: 'https://openrouter.ai/keys',
    editableBaseURL: false,
    group: 'aggregator',
  },
  {
    id: 'ollama',
    name: 'Ollama（本地模型）',
    kind: 'openai-compatible',
    defaultBaseURL: 'http://127.0.0.1:11434/v1',
    requiresKey: false,
    editableBaseURL: true,
    group: 'local',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio（本地模型）',
    kind: 'openai-compatible',
    defaultBaseURL: 'http://127.0.0.1:1234/v1',
    requiresKey: false,
    editableBaseURL: true,
    group: 'local',
  },
  {
    id: 'custom',
    name: '自定义 OpenAI 兼容接口',
    kind: 'openai-compatible',
    requiresKey: false,
    editableBaseURL: true,
    group: 'custom',
  },
];

export function getPreset(id: string): ProviderPreset | undefined {
  return providerPresets.find((preset) => preset.id === id);
}
